import logging
from fastapi import APIRouter, HTTPException
from fastapi.responses import PlainTextResponse
from dataclasses import asdict

from core.intelligence.session_summarizer import SessionSummarizer, SessionSummary
from core.errors import handle_exception

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/session", tags=["session"])

summarizer = SessionSummarizer()

@router.get("/{session_id}/summary", response_model=dict)
async def get_session_summary(session_id: str):
    """Retrieve the JSON summary of a session."""
    try:
        summary: SessionSummary = await summarizer.summarize(session_id)
        # If no steps were found, it means the session likely doesn't exist or is empty
        if summary.total_steps == 0 and summary.errors_detected == 0:
            raise HTTPException(status_code=404, detail=f"Session {session_id} not found or has no actions")
            
        return {
            "status": "success",
            "data": asdict(summary)
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching session summary for {session_id}: {e}")
        return handle_exception(e)

@router.get("/{session_id}/summary.md", response_class=PlainTextResponse)
async def get_session_summary_markdown(session_id: str):
    """Retrieve a formatted Markdown report of a session."""
    try:
        summary: SessionSummary = await summarizer.summarize(session_id)
        if summary.total_steps == 0 and summary.errors_detected == 0:
            raise HTTPException(status_code=404, detail=f"Session {session_id} not found or has no actions")
            
        md = f"""# Session Summary Report: {summary.session_id}

**Generated At:** {summary.generated_at}
**Task Type:** {summary.task_type}
**Duration:** {summary.duration_seconds} seconds

## Execution Metrics
- **Total Steps Logged:** {summary.total_steps}
- **Steps Completed:** {summary.steps_completed}

## Guidance & Errors
- **Total Guidance Delivered:** {summary.total_guidance_delivered}
- **Average Guidance Confidence:** {summary.avg_confidence}
- **Errors Detected:** {summary.errors_detected}
- **Errors Resolved:** {summary.errors_resolved}
- **Most Common Error:** {summary.most_common_error_type}

---
*Auto-generated by Execra Intelligence Layer*
"""
        return md
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating markdown summary for {session_id}: {e}")
        raise HTTPException(status_code=500, detail="Internal server error generating summary")
